# Generated by Django 5.1.6 on 2025-03-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('master_pw', models.CharField(max_length=128)),
                ('master_name', models.CharField(max_length=10)),
                ('master_phonenumber', models.CharField(max_length=15)),
                ('master_grade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='RoadReport',
            fields=[
                ('roadreport_num', models.AutoField(primary_key=True, serialize=False)),
                ('roadreport_id', models.CharField(max_length=100, unique=True)),
                ('roadreport_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('roadreport_damagetype', models.CharField(max_length=50, null=True)),
                ('roadreport_status', models.CharField(max_length=20, null=True)),
                ('roadreport_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('roadreport_region', models.CharField(max_length=255, null=True)),
                ('roadreport_direction', models.FloatField(blank=True, null=True)),
                ('roadreport_speed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roadreport',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=10)),
                ('user_age', models.PositiveIntegerField()),
                ('user_phonenumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userhistory_start', models.CharField(max_length=255)),
                ('userhistory_end', models.CharField(max_length=255)),
                ('userhistory_via', models.CharField(max_length=255)),
                ('userhistory_searchtime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_records', to='jolupapp.users')),
            ],
            options={
                'db_table': 'userhistory',
            },
        ),
    ]
