# Generated by Django 5.1.6 on 2025-03-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='userhistory_end',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='userhistory_start',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='userhistory_via',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
