# Generated by Django 5.1.6 on 2025-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadreport',
            name='roadreport_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
