# Generated by Django 5.1.6 on 2025-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0002_alter_roadreport_roadreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadreport',
            name='roadreport_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='roadreport_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
