# Generated by Django 5.1.6 on 2025-03-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0003_alter_roadreport_roadreport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadreport',
            name='roadreport_region',
        ),
    ]
