# Generated by Django 5.1.6 on 2025-03-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0004_remove_roadreport_roadreport_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadreport',
            old_name='roadreport_id',
            new_name='roadreport_latlng',
        ),
    ]
