# Generated by Django 5.1.6 on 2025-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0005_rename_roadreport_id_roadreport_roadreport_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadreport',
            name='roadreport_status',
            field=models.CharField(blank=True, default='접수됨', max_length=20, null=True),
        ),
    ]
