# Generated by Django 5.1.6 on 2025-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0006_alter_roadreport_roadreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadreport',
            name='roadreport_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
