# Generated by Django 5.1.6 on 2025-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0007_roadreport_roadreport_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadreport',
            name='roadreport_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
