# Generated by Django 5.1.6 on 2025-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0008_alter_roadreport_roadreport_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocache_latlng', models.CharField(max_length=100, unique=True)),
                ('geocache_address', models.CharField(max_length=255)),
                ('geocache_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'geocache',
            },
        ),
    ]
