# Generated by Django 5.1.6 on 2025-07-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0009_geocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='geocache_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocache',
            name='geocache_damagetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
