# Generated by Django 5.1.6 on 2025-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0010_geocache_geocache_count_geocache_geocache_damagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sagoNo', models.CharField(max_length=20, unique=True)),
                ('sido', models.CharField(max_length=50)),
                ('sigungu', models.CharField(max_length=50)),
                ('sagoDetail', models.CharField(max_length=50)),
                ('sagoDate', models.CharField(max_length=20)),
                ('no', models.IntegerField()),
                ('dong', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subsidence_report',
            },
        ),
    ]
