# Generated by Django 5.1.6 on 2025-08-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0011_subsidencereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidencereport',
            name='id',
        ),
        migrations.AddField(
            model_name='subsidencereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsidencereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='dong',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='sagoDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='sagoDetail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='sagoNo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='sido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subsidencereport',
            name='sigungu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
