# Generated by Django 5.1.6 on 2025-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolupapp', '0012_remove_subsidencereport_id_subsidencereport_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GGSubsidenceReport',
            fields=[
                ('sagoNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sido', models.CharField(blank=True, max_length=50, null=True)),
                ('sigungu', models.CharField(blank=True, max_length=50, null=True)),
                ('dong', models.CharField(blank=True, max_length=50, null=True)),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('sagoDate', models.CharField(blank=True, max_length=20, null=True)),
                ('restoreState', models.CharField(blank=True, max_length=50, null=True)),
                ('sagoDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gg_subsidence_report',
            },
        ),
    ]
