# -*- coding: utf-8 -*-
"""DoroSeeV1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRPJ2yDZOzXs_RTvw6V_CNu46B3V9qIG
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import zipfile

# 압축 파일 경로
zip_path = "/content/drive/MyDrive/DoroSeeV1/DoroSee.v2-doroseev1.yolov5pytorch.zip"
extract_path = "/content/DoroSeeV1"  # 압축을 풀 경로

# 압축 해제
os.makedirs(extract_path, exist_ok=True)
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os
import zipfile

# YOLO 데이터셋이 저장된 Google Drive 경로 설정
dataset_path = "/content/drive/MyDrive/DoroSeeV1/DoroSee.v2-doroseev1.yolov5pytorch.zip"
extract_path = "/content/DoroSeeV1"  # 압축 해제할 경로

# 압축 해제
os.makedirs(extract_path, exist_ok=True)
with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("📂 압축 해제된 폴더 내용:")
print(os.listdir(extract_path))

import os

# 경로 설정
data_yaml_path = "/content/DoroSeeV1/DoroSee.v2-doroseev1.yolov5pytorch/data.yaml"
directory = os.path.dirname(data_yaml_path)

# 경로가 없으면 생성
os.makedirs(directory, exist_ok=True)

# 수정된 yaml 내용
yaml_content = """train: /content/DoroSeeV1/DoroSee.v2-doroseev1.yolov5pytorch/train/images
val: /content/DoroSeeV1/DoroSee.v2-doroseev1.yolov5pytorch/valid/images
test: /content/DoroSeeV1/DoroSee.v2-doroseev1.yolov5pytorch/test/images

nc: 2
names: ['Crack', 'pothole']

roboflow:
  workspace: dorosee
  project: dorosee
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/dorosee/dorosee/dataset/2
"""

# 수정된 yaml 파일로 저장
with open(data_yaml_path, "w") as f:
    f.write(yaml_content)

data_yaml_path = "/content/DoroSeeV1/data.yaml"

with open(data_yaml_path, "r") as f:
    print(f.read())

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5.git
# %cd yolov5
!pip install -r requirements.txt  # 필요한 라이브러리 설치

!python train.py --img 640 --batch 32 --epochs 100 --data "/content/DoroSeeV1/data.yaml" --weights yolov5s.pt